# Generated by Django 5.1 on 2024-08-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_category_alter_customeuser_user_type_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'subadmin'), (1, 'admin')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsdetails',
            field=models.TextField(blank=True),
        ),
    ]
