# Generated by Django 5.1 on 2024-08-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_alter_customeuser_user_type_alter_news_newsdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_post_by',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_update_by',
        ),
    ]
