# Generated by Django 5.1 on 2024-08-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_remove_news_news_post_by_remove_news_news_update_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'subadmin')], default=1, max_length=100),
        ),
    ]
